spring:
  application:
  name: demoDatabase
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: UTC+7
      dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    user:
      name: admin
      password: 1234
springdoc:
  swagger-ui:
    path: swagger-ui.html
    operations-sorter: method

logging:
  level:
    org:
      springframework:
        web: DEBUG
    hibernate: ERROR